-- MySQL Script generated by MySQL Workbench
-- ven. 29 sept. 2017 23:16:32 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `idorganization` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `website_url` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `idtwet` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(600) NULL,
  PRIMARY KEY (`idtwet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `organization_idorganization` INT NOT NULL,
  `tweet_idtwet` INT NOT NULL,
  PRIMARY KEY (`iduser`, `organization_idorganization`, `tweet_idtwet`),
  INDEX `fk_user_organization1_idx` (`organization_idorganization` ASC),
  INDEX `fk_user_tweet1_idx` (`tweet_idtwet` ASC),
  CONSTRAINT `fk_user_organization1`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `mydb`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tweet1`
    FOREIGN KEY (`tweet_idtwet`)
    REFERENCES `mydb`.`tweet` (`idtwet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
