-- MySQL Script generated by MySQL Workbench
-- lun. 02 oct. 2017 09:59:37 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `idorganization` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `website_url` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganization`))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `idtwet` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(600) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idtwet`),
  INDEX `fk_tweet_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_tweet_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_organization` (
  `user_iduser` INT NOT NULL,
  `organization_idorganization` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `organization_idorganization`),
  INDEX `fk_user_has_organization_organization1_idx` (`organization_idorganization` ASC),
  INDEX `fk_user_has_organization_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_organization_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_organization_organization1`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `mydb`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
